taigaio/taiga

python/apps/taiga/src/taiga/routers/loader.py
python/apps/taiga/src/taiga/routers/routes.py
python/apps/taiga/src/taiga/users/api/__init__.py
python/apps/taiga/src/taiga/users/api/validators/__init__.py
python/apps/taiga/src/taiga/users/serializers/__init__.py
python/apps/taiga/src/taiga/users/serializers/services.py
python/apps/taiga/src/taiga/users/services/__init__.py
python/apps/taiga/src/taiga/workspaces/invitations/api/__init__.py
python/apps/taiga/src/taiga/workspaces/invitations/events/__init__.py
python/apps/taiga/src/taiga/workspaces/invitations/permissions.py
python/apps/taiga/src/taiga/workspaces/invitations/repositories.py
python/apps/taiga/src/taiga/workspaces/invitations/serializers/__init__.py
python/apps/taiga/src/taiga/workspaces/invitations/serializers/nested.py
python/apps/taiga/src/taiga/workspaces/invitations/serializers/services.py
python/apps/taiga/src/taiga/workspaces/invitations/services/__init__.py
python/apps/taiga/src/taiga/workspaces/invitations/services/exceptions.py
python/apps/taiga/tests/integration/taiga/users/test_api.py
python/apps/taiga/tests/integration/taiga/workspaces/invitations/test_api.py
python/apps/taiga/tests/integration/taiga/workspaces/invitations/test_repositories.py
python/apps/taiga/tests/unit/taiga/users/test_services.py
python/apps/taiga/tests/unit/taiga/workspaces/invitations/test_services.py
python/docs/events.md
python/docs/postman/taiga.postman_collection.json
python/docs/postman/taiga.postman_collection_e2e.json

This PR allows to accept a workspace invitation, both for existing members and new users in Taiga.
https://tree.taiga.io/project/taiga-next/us/1593?milestone=345963

feat(workspaces): accept a workspace invitation from token

---

javascript/apps/taiga/src/app/modules/project/story-detail/components/story-detail-description/story-detail-description.component.css
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/actions/story-detail.actions.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/effects/story-detail.effects.spec.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/effects/story-detail.effects.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/reducers/story-detail.reducer.ts
javascript/apps/taiga/src/app/modules/project/story-detail/directives/story-comments-pagination.directive.spec.ts
javascript/apps/taiga/src/app/modules/project/story-detail/directives/story-comments-pagination.directive.ts
javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.component.css
javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.component.html
javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.component.ts
javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.module.ts
javascript/apps/taiga/src/app/shared/comments/comments.component.css
javascript/apps/taiga/src/app/shared/comments/comments.component.html
javascript/apps/taiga/src/app/shared/comments/comments.component.ts
javascript/apps/taiga/src/app/shared/comments/components/comment skeleton/comment-skeleton.component.css
javascript/apps/taiga/src/app/shared/comments/components/comment skeleton/comment-skeleton.component.html
javascript/apps/taiga/src/app/shared/comments/components/comment skeleton/comment-skeleton.component.ts
javascript/apps/taiga/src/app/shared/comments/components/comment-user-input/comment-user-input.component.css
javascript/apps/taiga/src/app/shared/comments/components/comment-user-input/comment-user-input.component.html
javascript/apps/taiga/src/app/shared/comments/components/comment-user-input/comment-user-input.component.ts
javascript/apps/taiga/src/app/styles/shared/button.css
javascript/apps/taiga/src/assets/i18n/comments/en-US.json
javascript/apps/taiga/src/assets/icons/sort-reverse.svg
javascript/apps/taiga/src/assets/icons/sort.svg
javascript/libs/api/src/lib/project/project-api.service.ts
javascript/libs/data/src/index.ts
javascript/libs/data/src/lib/user-comment.model.mock.ts
javascript/libs/data/src/lib/user-comment.model.ts

Test with https://github.com/taigaio/taiga/tree/us/3404/task/3673/list-comments

feat: add comments to story detail

---

.dockerignore
.gitignore
docker/.env.example
docker/docker-compose.yml
docker/images/Dockerfile.backend
docker/images/Dockerfile.frontend
docker/images/config.json.template
docker/images/config.sh
docker/images/nginx.conf
python/apps/taiga/src/taiga/__main__.py
python/apps/taiga/src/taiga/conf/__init__.py
python/apps/taiga/src/taiga/tasksqueue/commands.py
python/apps/taiga/tests/conf_django.py
python/docs/docker.md
python/docs/get-started-dev.md

This PR adds docker functionality for deployments.
How to review:

feat(docker): images and docker-compose.yml

---

python/docs/conventions/urls.conventions.md
python/docs/review-check-list.md

chore(doc): u#2032 t#3745 update convention urls and checklist

---

.github/workflows/javascript-front-e2e.yml
.github/workflows/javascript-front-tests.yml
javascript/config.example.json

"Running" e2e
https://github.com/taigaio/taiga/actions/runs/5330915456

fix: update e2e front github action

---

javascript/apps/taiga-e2e/src/e2e/project/kanban/kanban.cy.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/create-status/kanban-create-status.component.css
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/create-status/kanban-create-status.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/create-status/kanban-create-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/create-story-inline/kanban-create-story-inline.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/workflow/kanban-workflow.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/workflow/kanban-workflow.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/actions/kanban.actions.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/effects/kanban.effects.spec.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/effects/kanban.effects.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/reducers/kanban.reducer.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/project-feature-kanban.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/project-feature-kanban.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/project-feature-kanban.module.ts
javascript/apps/taiga/src/app/modules/project/story-detail/components/story-detail-title/story-detail-title.component.html
javascript/apps/taiga/src/assets/i18n/en-US.json
javascript/apps/taiga/src/assets/i18n/kanban/en-US.json
javascript/libs/api/src/lib/project/project-api.service.ts
javascript/libs/data/src/lib/status.model.ts

It has to be tested running `back` on the following branch: us/2032/task/3721/create-status-endpoint

feat(front): u#2032 t#3724 create status

---

javascript/apps/taiga/src/app/modules/project/data-access/+state/actions/project.actions.ts
javascript/apps/taiga/src/app/modules/project/feature-shell/project-feature-shell.component.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/effects/story-detail-comments.effects.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/effects/story-detail.effects-comments.spec.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/reducers/story-detail.reducer.spec.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/reducers/story-detail.reducer.ts

Test with https://github.com/taigaio/taiga/pull/354

feat(comments): story detail comment event

---

javascript/apps/taiga/src/app/modules/project/feature-kanban/components/create-status/kanban-create-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/delete-status/delete-status.component.css
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/delete-status/delete-status.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/delete-status/delete-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/edit-status/edit-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/empty/kanban-empty.component.css
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/empty/kanban-empty.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/empty/kanban-empty.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/status/kanban-status.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/status/kanban-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/workflow/kanban-workflow.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/workflow/kanban-workflow.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/actions/kanban.actions.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/effects/kanban.effects.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/reducers/kanban.reducer.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/selectors/kanban.selectors.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/directives/status-scroll-dynamic-height/scroll-dynamic-height.directive.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/project-feature-kanban.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/project-feature-kanban.module.ts
javascript/apps/taiga/src/assets/i18n/en-US.json
javascript/apps/taiga/src/assets/i18n/kanban/en-US.json
javascript/apps/taiga/src/assets/images/kanban-empty.svg
javascript/libs/api/src/lib/project/project-api.service.ts
javascript/libs/ui/src/lib/inputs/inputs.module.ts
javascript/libs/ui/src/lib/inputs/radio/radio.component.css
javascript/libs/ui/src/lib/inputs/radio/radio.component.html
javascript/libs/ui/src/lib/inputs/radio/radio.component.ts

api branch -> us/2035/task/3787/delete-status

feat(front): u#2035 t#3773 delete status modal

---

python/apps/taiga/src/taiga/comments/events.py
python/apps/taiga/src/taiga/comments/repositories.py
python/apps/taiga/src/taiga/comments/serializers.py
python/apps/taiga/src/taiga/comments/services.py
python/apps/taiga/src/taiga/stories/comments/api.py
python/apps/taiga/src/taiga/stories/comments/events/__init__.py
python/apps/taiga/src/taiga/stories/comments/events/content.py
python/apps/taiga/tests/integration/taiga/comments/test_repositories.py
python/apps/taiga/tests/integration/taiga/stories/comments/test_api.py
python/apps/taiga/tests/unit/taiga/comments/test_services.py
python/docs/events.md
python/docs/postman/taiga.postman_collection.json
python/docs/postman/taiga.postman_collection_e2e.json

feat(comments): u#3412 t#3786 endpoint patch comment

---

javascript/apps/taiga/src/app/modules/project/feature-kanban/components/edit-status/edit-status.component.css
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/edit-status/edit-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/status/kanban-status.component.html
javascript/apps/taiga/src/app/modules/project/feature-kanban/components/status/kanban-status.component.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/actions/kanban.actions.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/effects/kanban.effects.ts
javascript/apps/taiga/src/app/modules/project/feature-kanban/data-access/+state/reducers/kanban.reducer.ts
javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/reducers/story-detail.reducer.ts

This PR includes both design reviews:
- https://tree.taiga.io/project/taiga-next/task/3827
- https://tree.taiga.io/project/taiga-next/task/3830

fix(kanban): design review

---

javascript/apps/taiga/src/app/modules/project/story-detail/data-access/+state/reducers/story-detail.reducer.ts

https://tree.taiga.io/project/taiga-next/task/3827

fix(kanban): design review II

---

javascript/apps/taiga/src/app/shared/comments/components/comment-user-input/comment-user-input.component.ts

This pr only contains the fix for the front side

fix(comments): i#3836 dont allow blank space or line break comments

---

python/apps/taiga/src/taiga/projects/projects/services/__init__.py
python/apps/taiga/tests/unit/taiga/projects/projects/test_services.py

This PR deletes the pj-logo after deleting the project.
How to review:
**Note** I'm guessing the task should be more general.

fix(project): i#3880 delete logo file after deleting project

---

javascript/apps/taiga/src/app/modules/workspace/feature-list/components/workspace-item/workspace-item.component.spec.ts
javascript/apps/taiga/src/app/modules/workspace/feature-list/components/workspace-item/workspace-item.component.ts
javascript/apps/taiga/src/app/modules/workspace/feature-list/components/workspace/workspace.component.html
python/apps/taiga/src/taiga/workspaces/workspaces/repositories.py
python/apps/taiga/tests/integration/taiga/workspaces/workspaces/test_repositories.py

i#3770 wks projects per row

---

python/apps/taiga/src/taiga/stories/mediafiles/api.py

fix(stories.mediafiles): i#3904 external user can add images to a comment

---

python/apps/taiga/src/taiga/workflows/api/validators.py
python/apps/taiga/tests/integration/taiga/workflows/test_api.py

This PR fixes the stories migration (to another specified status) when deleting its container workflow status.
https://tree.taiga.io/project/taiga-next/issue/3890
**Note**: The error was due to a double validation error on the B64UUID field, when it was decoded to get the final UUID. The first validation it returned a valid UUID, but the second one failed, being captured by the `except` to return a None instead. This is the reason why it's not resolved in the `base.validator.fields.B64UUID` class
Using the frontend (main branch), or Postman, delete any workflow status from any kanban, specifying its stories to get moved to another status. **Don't forget to refresh the page**.

issue(back): i#3890 stories don't get moved when deleting its status

---

javascript/libs/data/src/lib/auth.model.ts

I know, it's a very, very simple PR, but I wanted to give you a present while I am on holidays ❤️

chore: remove unneeded interface

---

javascript/apps/taiga/src/app/modules/auth/feature-sign-up/components/signup/signup.component.css
javascript/apps/taiga/src/app/modules/auth/feature-sign-up/components/signup/signup.component.html

Fixes https://tree.taiga.io/project/taiga-next/issue/3882

fix: #3882 move full name on top of input fields on register

---

javascript/apps/taiga/src/app/shared/comments/components/comment-detail/comment-detail.component.html
javascript/apps/taiga/src/app/shared/comments/components/comment-detail/comment-detail.component.ts
javascript/apps/taiga/src/assets/i18n/comments/en-US.json

fixes https://tree.taiga.io/project/taiga-next/issue/3848

fix: i#3848 better copy in the comment deletion

---

javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.component.css
javascript/apps/taiga/src/app/modules/project/story-detail/story-detail.component.html

fixes https://tree.taiga.io/project/taiga-next/issue/3646

fix: i#3646 story number too small

---

javascript/libs/ui/src/lib/tooltip/tooltip.component.ts
javascript/libs/ui/src/lib/tooltip/tooltip.directive.ts
javascript/libs/ui/src/lib/tooltip/tooltip.service.ts
javascript/libs/ui/src/lib/tooltip/tooltip.spec.ts

Fixes microscroll on webkit and blink, meaning chrome, safari and derivates.

fix: #3905 micro scroll on webkit and blink

---

python/apps/taiga/src/taiga/comments/repositories.py
python/apps/taiga/src/taiga/comments/services.py
python/apps/taiga/src/taiga/permissions/services.py
python/apps/taiga/src/taiga/projects/memberships/repositories.py
python/apps/taiga/src/taiga/projects/memberships/services/__init__.py
python/apps/taiga/src/taiga/stories/assignments/repositories.py
python/apps/taiga/src/taiga/stories/assignments/services/__init__.py
python/apps/taiga/src/taiga/stories/stories/repositories.py
python/apps/taiga/src/taiga/stories/stories/services/__init__.py
python/apps/taiga/src/taiga/workflows/repositories.py
python/apps/taiga/src/taiga/workflows/services/__init__.py
python/apps/taiga/src/taiga/workspaces/memberships/services/__init__.py
python/apps/taiga/tests/integration/taiga/stories/assignments/test_repositories.py
python/apps/taiga/tests/unit/taiga/comments/test_services.py
python/apps/taiga/tests/unit/taiga/stories/assignments/test_services.py

This PR removes `sync_to_async` functions from permissions/services and applies the consequent fixes where needed.

chore(permissions): i#3924 fix permissions services

---

python/apps/taiga/tests/conftest.py
python/apps/taiga/tests/utils/testclient.py

running:
```
python -m pytests --help
```

fix(test): error initializing tests

---

python/apps/taiga/src/taiga/workflows/api/__init__.py
python/apps/taiga/src/taiga/workflows/api/validators.py
python/apps/taiga/src/taiga/workflows/events/__init__.py
python/apps/taiga/src/taiga/workflows/events/content.py
python/apps/taiga/src/taiga/workflows/models.py
python/apps/taiga/src/taiga/workflows/repositories.py
python/apps/taiga/src/taiga/workflows/services/__init__.py
python/apps/taiga/tests/integration/taiga/workflows/test_api.py
python/apps/taiga/tests/integration/taiga/workflows/test_repositories.py
python/apps/taiga/tests/unit/taiga/workflows/test_services.py
python/docs/events.md
python/docs/postman/taiga.postman_collection.json
python/docs/postman/taiga.postman_collection_e2e.json

feat(workflows): u#2860 t#4028 update workflow endpoint

---

python/apps/taiga/src/taiga/stories/stories/notifications/__init__.py
python/apps/taiga/src/taiga/stories/stories/notifications/content.py
python/apps/taiga/src/taiga/stories/stories/services/__init__.py
python/apps/taiga/tests/unit/taiga/stories/stories/test_services.py

<div align="center">
</div>
Notify to the creator of the story when it has been deleted.
- As 1user create a story and delete it as 2user, one notification must be created.

[back] feat(notifications): u#3207 notify when a story has been deleted

---

python/apps/taiga/src/taiga/stories/stories/events/content.py
python/apps/taiga/src/taiga/stories/stories/repositories.py
python/apps/taiga/src/taiga/stories/stories/serializers/__init__.py
python/apps/taiga/src/taiga/stories/stories/services/__init__.py
python/apps/taiga/src/taiga/workflows/api/__init__.py
python/apps/taiga/src/taiga/workflows/api/validators.py
python/apps/taiga/src/taiga/workflows/events/__init__.py
python/apps/taiga/src/taiga/workflows/events/content.py
python/apps/taiga/src/taiga/workflows/repositories.py
python/apps/taiga/src/taiga/workflows/serializers/__init__.py
python/apps/taiga/src/taiga/workflows/serializers/services.py
python/apps/taiga/src/taiga/workflows/services/__init__.py
python/apps/taiga/src/taiga/workflows/services/exceptions.py
python/apps/taiga/tests/integration/taiga/stories/stories/test_repositories.py
python/apps/taiga/tests/integration/taiga/workflows/test_api.py
python/apps/taiga/tests/integration/taiga/workflows/test_repositories.py
python/apps/taiga/tests/unit/taiga/workflows/test_services.py
python/docs/events.md
python/docs/postman/taiga.postman_collection.json
python/docs/postman/taiga.postman_collection_e2e.json

This PR adds the endpoint to delete a workflow, providing the option to move the workflow statuses it may content to another workflow in the same project (with the `moveTo` parameter).
DELETE `/projects/{{pj-id}}/workflows/{{wf-slug}}?moveTo={{wf-slug}}`
https://tree.taiga.io/project/taiga-next/us/2859?milestone=360069
Delete a workflow without a moveTo param
Delete a workflow providing a `moveTo` workflow with existing statuses
Delete a workflow providing a `moveTo` workflow with no existing statuses (empty workflow)
Error responses

feat(workflows): add the endpoint to delete a workflow

---

javascript/apps/taiga/src/app/shared/navigation/notification/notification.component.ts
javascript/libs/data/src/lib/notification.model.ts
python/apps/taiga/src/taiga/stories/stories/notifications/__init__.py
python/apps/taiga/src/taiga/stories/stories/notifications/content.py

This PR fixes a typo, and affects the js part as well. It's in draft mode until it's consolidated from both parts.

chore: change projects with project
