taigaio/taiga

python/apps/taiga/src/taiga/permissions/validators/fields.py, python/apps/taiga/tests/unit/taiga/permissions/test_validators.py
This PR guarantees that a user cannot configure at the same time "not-view-story" and "can-comment-story" as both are incompatible. It also fixes a redundant test.
How to validate:
=> check incompatible permissions for comment_story

python/apps/taiga/src/taiga/commons/__init__.py, python/apps/taiga/src/taiga/commons/invitations.py, python/apps/taiga/src/taiga/conf/__init__.py, python/apps/taiga/src/taiga/projects/invitations/services/__init__.py, python/apps/taiga/src/taiga/workspaces/invitations/services/__init__.py, python/apps/taiga/tests/unit/taiga/projects/invitations/test_services.py, python/apps/taiga/tests/unit/taiga/workspaces/invitations/test_services.py
This PR has a little refactor over "_is_spam" check:
- new module `commons` for Taiga common stuff
- both projects and workspaces use this new general check
- unify settings as well
How to review:
=> chore(invitations): generalize is_spam for projects and workspaces

python/apps/taiga/src/taiga/base/api/ordering.py, python/apps/taiga/src/taiga/base/sampledata/factories.py, python/apps/taiga/src/taiga/comments/repositories.py, python/apps/taiga/src/taiga/comments/serializers/__init__.py, python/apps/taiga/src/taiga/comments/serializers/services.py, python/apps/taiga/src/taiga/comments/services.py, python/apps/taiga/src/taiga/exceptions/api/__init__.py, python/apps/taiga/src/taiga/routers/loader.py, python/apps/taiga/src/taiga/routers/routes.py, python/apps/taiga/src/taiga/stories/comments/__init__.py, python/apps/taiga/src/taiga/stories/comments/api.py, python/apps/taiga/src/taiga/stories/comments/validators.py, python/apps/taiga/src/taiga/stories/stories/models.py, python/apps/taiga/tests/integration/taiga/comments/__init__.py, python/apps/taiga/tests/integration/taiga/comments/test_repositories.py, python/apps/taiga/tests/integration/taiga/stories/comments/__init__.py, python/apps/taiga/tests/integration/taiga/stories/comments/test_api.py, python/apps/taiga/tests/unit/taiga/base/api/test_ordering.py, python/apps/taiga/tests/unit/taiga/comments/__init__.py, python/apps/taiga/tests/unit/taiga/comments/test_services.py, python/apps/taiga/tests/utils/factories/__init__.py, python/apps/taiga/tests/utils/factories/comments.py, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json
This PR adds the endpoint to list the comments for a Story: `GET projects/<id>/stories/<ref>/comments`
- It should be paginated, and accept a param to sort by newest/oldest comments according to the creation_date.
- It's been added a new group in OpenApi doc to group the comments entries (for stories and other model's contentTypes)
Ensure you have the last sample data in your db, and use the django admin to identify a story with some comments.
You may find useful this query to identify the most commented stories and the projects they belong to:
```sql
select pp."name", ss.description, ss.ref, count(cc.id) from comments_comment cc
join stories_story ss on ss.id = cc.object_id
join projects_project pp on pp.id = ss.project_id 
group by ss.id, pp.id
order by count(pp.id) desc
```
=> feat(comments): list story comments

python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/api/validators.py, python/apps/taiga/src/taiga/workflows/events/__init__.py, python/apps/taiga/src/taiga/workflows/repositories.py, python/apps/taiga/src/taiga/workflows/serializers/services.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/src/taiga/workflows/services/exceptions.py, python/apps/taiga/tests/integration/taiga/workflows/test_api.py, python/apps/taiga/tests/integration/taiga/workflows/test_repositories.py, python/apps/taiga/tests/unit/taiga/workflows/test_services.py, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json, python/docs/postman/taiga.postman_environment.json, python/docs/workflows/requirements.workflow.md
This PR creates the endpoint that allows to update the workflow status's name.
> **PATCH** /projects/{{pj-id}}/workflows/{{wf-slug}}/statuses/{{ws-slug}}
**NOTE**: The events involved within this endpoint will come in another PR soon
Create a new workflow status, and validate that:
=> feat(status): create the endpoint to update the status name

python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/events/__init__.py, python/apps/taiga/src/taiga/workflows/events/content.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/tests/unit/taiga/workflows/test_services.py
¡eventazo!
This PR adds an event when the workflow status is changed.
How to review:
mind! it also changes "workflow_events" for "workflows_events" following the naming convention.
=> feat(workflow status): u#2033 emit event when workflow status is updated

python/apps/taiga/src/taiga/base/db/models/__init__.py, python/apps/taiga/src/taiga/comments/events.py, python/apps/taiga/src/taiga/comments/models.py, python/apps/taiga/src/taiga/comments/repositories.py, python/apps/taiga/src/taiga/comments/services.py, python/apps/taiga/src/taiga/permissions/__init__.py, python/apps/taiga/src/taiga/permissions/services.py, python/apps/taiga/src/taiga/projects/memberships/api/__init__.py, python/apps/taiga/src/taiga/stories/comments/api.py, python/apps/taiga/src/taiga/stories/comments/events/__init__.py, python/apps/taiga/src/taiga/stories/comments/events/content.py, python/apps/taiga/tests/integration/taiga/comments/test_repositories.py, python/apps/taiga/tests/integration/taiga/stories/comments/test_api.py, python/apps/taiga/tests/unit/taiga/base/api/test_permissions.py, python/apps/taiga/tests/unit/taiga/comments/test_services.py, python/apps/taiga/tests/unit/taiga/permissions/test_services.py, python/docs/events.md, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json, python/docs/postman/taiga.postman_environment.json
This PR add a new endpoint to delete a comment (with his event) and apply a minor refactor to the comment module and to a permission class.
Only project admins and the comment owner can delete it.
=> feat(comments): u#3411 delete comment API endpoint

python/apps/taiga/src/taiga/stories/stories/services/__init__.py, python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/api/validators.py, python/apps/taiga/src/taiga/workflows/events/__init__.py, python/apps/taiga/src/taiga/workflows/events/content.py, python/apps/taiga/src/taiga/workflows/models.py, python/apps/taiga/src/taiga/workflows/repositories.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/src/taiga/workflows/services/exceptions.py, python/apps/taiga/tests/integration/taiga/workflows/test_api.py, python/apps/taiga/tests/integration/taiga/workflows/test_repositories.py, python/apps/taiga/tests/unit/taiga/stories/stories/test_services.py, python/apps/taiga/tests/unit/taiga/workflows/test_services.py, python/docs/events.md, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json
This PR allows to delete a workspace status, giving the option to avoid deleting its stories by moving them to another valid workspace status (in the same workflow).
`DELETE /projects/TH4C5hvNEe61Tw3m0DW-EQ/workflows/main/statuses/Closed?moveTo=closed`
For the next validations use the api in conjunction with this other frontend's branch: `us/2035/task/3773/delete-status-modal`.
As a project admin, go to the kanban and create two stories for every workflow status in the kanban. 
Verify the status is deleted, but their stories have been moved to the specified status (at the end of previous stories and in the same previous order). It gives a 204 (no content)
Verify that both the status and its stories are deleted from the database. The kanban should be empty.
Using the api, verify the error …
=> feat(status): delete a workflow status

javascript/apps/taiga/src/app/modules/project/feature-shell/project-feature-shell.component.ts, python/apps/taiga/src/taiga/stories/assignments/events/__init__.py, python/docs/events.md
This PR solves an event naming problem.
How to test:
=> fix(events): i#3805 emit event with proper name

python/apps/taiga/src/taiga/projects/invitations/services/__init__.py, python/apps/taiga/src/taiga/workspaces/invitations/services/__init__.py, python/apps/taiga/tests/unit/taiga/projects/invitations/test_services.py, python/apps/taiga/tests/unit/taiga/workspaces/invitations/test_services.py
This PR solves the same issue for project and workspace invitations.
Current situation: we only emit event if we have emails to send
Problem: in an spam situation, we don't send email (ok) but we don't emit event either (not ok)
The solution consists on checking if there are new/updated invitations (no matter if they send email) and emit event in this case.
How to test:
=> fix(invitations): i#3674 emit event when pj/ws invitations are updated

python/apps/taiga/src/taiga/base/utils/images.py, python/apps/taiga/src/taiga/conf/images.py, python/apps/taiga/src/taiga/projects/projects/api/validators.py, python/apps/taiga/tests/unit/taiga/projects/projects/test_validators.py
bye bye, SVG
This PR makes the API return an error if the user tries to upload an svg file in the project logo.
How to review:
=> fix(images): i#2675 the API now prevents from uploading SVG format

python/apps/taiga/src/taiga/base/api/headers.py, python/apps/taiga/src/taiga/comments/repositories.py, python/apps/taiga/src/taiga/comments/services.py, python/apps/taiga/src/taiga/main.py, python/apps/taiga/src/taiga/stories/comments/api.py, python/apps/taiga/tests/integration/taiga/comments/test_repositories.py, python/apps/taiga/tests/integration/taiga/stories/comments/test_api.py, python/apps/taiga/tests/unit/taiga/comments/test_services.py
This PR adds a new header in the response of list comments, so the user can have both:
- total comments including deleted (for pagination purposes)
- total comments "only active" (for user purposes)
How to review:
=> add total-objs to pagination response

python/apps/taiga/src/taiga/projects/projects/repositories.py, python/apps/taiga/src/taiga/users/api/__init__.py, python/apps/taiga/src/taiga/users/serializers/__init__.py, python/apps/taiga/src/taiga/users/serializers/nested.py, python/apps/taiga/src/taiga/users/serializers/services.py, python/apps/taiga/src/taiga/users/services/__init__.py, python/apps/taiga/src/taiga/workspaces/workspaces/repositories.py, python/apps/taiga/tests/integration/taiga/projects/projects/test_repositories.py, python/apps/taiga/tests/integration/taiga/users/test_api.py, python/apps/taiga/tests/integration/taiga/workspaces/workspaces/test_repositories.py, python/apps/taiga/tests/unit/taiga/users/test_services.py, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json
This endpoint is for the "Before deleting..." modal.
Also change validate function in serializers because in this endpoint we need to serialize an id twice.
You need the next scenary:
- user1 and user2
- ws1 where user1 is the only ws-member
- pj1_ws1 where user1 is the only pj-member (admin)
- pj2_ws1 where user1 is the only pj-admin and user2 is pj-member
- ws2 where user1 and user2 are ws-members
- pj1_ws2 where user1 and user2 are pj-admins
- ws3 where user2 is ws-member
- pj1_ws3 where user1 is the only pj-admin and user2 is pj-member
- ws4 where user1 and user2 are ws-members
- pj1_ws4 where user1 and user2 are pj-admins
- pj2_ws4 where user1 is the only pj-admin and user2 is pj-member
- ws5 where user1 is the only ws-member without projects
In postman:
=> feat(user): delete info endpoint

python/apps/taiga/src/taiga/base/validators/fields.py, python/apps/taiga/src/taiga/projects/invitations/api/__init__.py, python/apps/taiga/src/taiga/projects/memberships/api/__init__.py, python/apps/taiga/src/taiga/projects/projects/api/__init__.py, python/apps/taiga/src/taiga/projects/roles/api.py, python/apps/taiga/src/taiga/stories/assignments/api/__init__.py, python/apps/taiga/src/taiga/stories/comments/api.py, python/apps/taiga/src/taiga/stories/mediafiles/api.py, python/apps/taiga/src/taiga/stories/stories/api/__init__.py, python/apps/taiga/src/taiga/users/api/__init__.py, python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/src/taiga/workspaces/invitations/api/__init__.py, python/apps/taiga/src/taiga/workspaces/workspaces/api/__init__.py, python/apps/taiga/tests/integration/taiga/projects/projects/test_api.py, python/apps/taiga/tests/integration/taiga/stories/mediafiles/test_api.py, python/apps/taiga/tests/integration/taiga/stories/stories/test_api.py, python/apps/taiga/tests/integration/taiga/workflows/test_api.py, python/apps/taiga/tests/integration/taiga/workspaces/invitations/test_api.py.orig, python/apps/taiga/tests/integration/taiga/workspaces/workspaces/test_api.py, python/apps/taiga/tests/unit/taiga/base/test_validators.py, python/apps/taiga/tests/unit/taiga/stories/stories/test_validators.py, python/apps/taiga/tests/utils/bad_params.py, python/docs/conventions/test_api.convetions.md
This PR fixes returning uuids on the 404 errors where those endpoints were really managing b64uuids on their requests. 
The B64UUID's validator has been changed to remove the try/expect protection when trying to get the UUID, and letting the pydantic ValidationError to arise.
As result, when we previously return just a 404, we may also return a 422 when the provided b64id is not valid.
- The Openapi errors in the affected endpoints has been fixed to include the new 422 response (and to follow the new convention)
- Tests have been fixed, including new tests for the new 422 cases (and changed to follow the new convenction)
- Error message in the responses won't show any id (the error originally)  because there's not a 1-to-1 relationship between `b64uuid's` and `uuid's` .
- It's been …
=> issue(b64uuid): i#3907 fix returning uuids on 404 errors

python/apps/taiga/src/taiga/comments/events.py, python/apps/taiga/src/taiga/comments/services.py, python/apps/taiga/src/taiga/permissions/services.py, python/apps/taiga/src/taiga/stories/comments/api.py, python/apps/taiga/src/taiga/stories/comments/events/__init__.py, python/apps/taiga/tests/unit/taiga/comments/test_services.py
This PR fixes a bug in the way we are generating the events for comments.
How to review:
=> i#3923 fix delete_comment service

python/apps/taiga/src/taiga/comments/models.py
- The constraint is not assigned to `constraints` attribute.
- The field should be "object_content_type" and not "content_type"
- If this constraint is applied, every related object (identify by "object_content_type" and "object_id") can only have one comment.
=> fix: remove invalid code

python/apps/taiga/src/taiga/stories/stories/api/__init__.py, python/apps/taiga/src/taiga/stories/stories/notifications/__init__.py, python/apps/taiga/src/taiga/stories/stories/notifications/content.py, python/apps/taiga/src/taiga/stories/stories/repositories.py, python/apps/taiga/src/taiga/stories/stories/services/__init__.py, python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/tests/integration/taiga/stories/stories/test_services.py, python/apps/taiga/tests/unit/taiga/stories/stories/test_services.py, python/apps/taiga/tests/unit/taiga/workflows/test_services.py
<div align="center">
</div>
This PR notifies assigned users and its creator when the story changes its status.
This can happen: 
- In kanban, when a story changes to another column.
- From the detail panel of a story, through the status selector.
- When a state is deleted and its stories are requested to move to another
- Manual test. Notifications must be created when some user...
=> [back] feat(notifications): u#2900 notify when the status of a story has changed

python/apps/taiga/src/taiga/notifications/api.py, python/apps/taiga/src/taiga/notifications/events/__init__.py, python/apps/taiga/src/taiga/notifications/events/content.py, python/apps/taiga/src/taiga/notifications/repositories.py, python/apps/taiga/src/taiga/notifications/services.py, python/apps/taiga/tests/integration/taiga/notifications/test_api.py, python/apps/taiga/tests/integration/taiga/notifications/test_repositories.py, python/apps/taiga/tests/unit/taiga/notifications/test_services.py, python/apps/taiga/tests/utils/factories/notifications.py, python/docs/events.md, python/docs/postman/taiga.postman_collection.json, python/docs/postman/taiga.postman_collection_e2e.json, python/docs/postman/taiga.postman_environment.json
<div align="center">
</div>
This PR add an endpoint to mark one notifications as read. It is a POST call with an empty body
```
POST /my/notifications/{id}/read
```
- Create a notification (assign a story to any user, not you).
- Call to the new endpoint (with postman or something similar)
- the response should contain the notification with the current datetime settled in `readAt`
- there is a new event `notifications.read` with a list of notifications ids marked as read
=>  [back] feat(notifications): u#2899 mark notification as read

python/apps/taiga/src/taiga/stories/stories/notifications/__init__.py, python/apps/taiga/src/taiga/stories/stories/notifications/content.py, python/apps/taiga/src/taiga/stories/stories/services/__init__.py, python/apps/taiga/tests/unit/taiga/stories/stories/test_services.py
This PR emits notifications after someone changes the story workflow (and status).
Who is notified?
- the story creator (given that she is not the one changing the story)
- each of the assigned user (except the one who is changing the story)
How to review:
=> feat(notifications): u#3985 notify when a story has changed workflow (and status)

python/apps/taiga/src/taiga/workflows/api/__init__.py, python/apps/taiga/src/taiga/workflows/repositories.py, python/apps/taiga/src/taiga/workflows/services/__init__.py, python/apps/taiga/tests/integration/taiga/workflows/test_repositories.py, python/apps/taiga/tests/unit/taiga/workflows/test_services.py
This PR avoids to preserve empty statuses (those ones without stories), when deleting a workflow and specifying to move its existing statuses.
=> feat(delete-worflow): move just not-empty statuses

python/apps/taiga/src/taiga/stories/stories/api/validators.py, python/apps/taiga/src/taiga/stories/stories/services/__init__.py, python/apps/taiga/tests/integration/taiga/stories/stories/test_api.py, python/apps/taiga/tests/unit/taiga/stories/stories/test_services.py
Avoids to update a status and a workflow simultaneously for a story. It's been fixed both in the api and the service layer.
[Reported issue](https://tree.taiga.io/project/taiga-next/issue/4114) in Taiga (see the comments).
```
// call api/v2/projects/FDx4mH1tEe6N1LQumfCfHA/stories/18
{
"ref": 18,
"version": 8,
"workflow": "new-workflow"
"status": "another-status-in-current-workflow",
}
```
=> issue(story): #4114 validate not being updated both workflow and status

python/apps/taiga/src/taiga/__main__.py, python/apps/taiga/src/taiga/commons/storage/commands.py, python/apps/taiga/src/taiga/conf/__init__.py, python/apps/taiga/src/taiga/conf/notifications.py, python/apps/taiga/src/taiga/conf/tasksqueue.py, python/apps/taiga/src/taiga/notifications/commands.py, python/apps/taiga/src/taiga/notifications/repositories.py, python/apps/taiga/src/taiga/notifications/services.py, python/apps/taiga/src/taiga/notifications/tasks.py, python/apps/taiga/tests/integration/taiga/notifications/test_repositories.py, python/apps/taiga/tests/unit/taiga/notifications/test_services.py
<div align=center>
</div>
A periodic task is created that will delete delete all notifications that have been read more than X minutes ago. (The frequency of the periodic task and time that the nitifications will be kept are configurable parameters).
There is a CLI command to remove read notifications too.
- Init:
- Set settings to remove notifications read before 2 minutes.
```
export TAIGA_NOTIFICATIONS__CLEAN_READ_NOTIFICATIONS_CRON= "* * * * *"
export TAIGA_NOTIFICATIONS__MINUTES_TO_STORE_READ_NOTIFICATIONS=1
```
- Open two frontend as 1user and 2user and go to the same kanban
- Test periodic task: 
- You have to create some notifications and mark as read. Then, wait a little bit (~ 2 minutes) and check the console logs to see the log entry of the periodic task runned.
- Test CLI: 
- …
=> [BACK] feat(notifications): u#3965 add a periodic task and a command to delete read notifications
